### ISSUE TITLE
UP9600

### ISSUE THREAD

**Issue by jalbarracinv** [vbguyny/c64kernel#1]
Hi, first of all thank you for your work. I've seen your posts in the lemon64 forum. kudos!
Did you find a way to make VICE emulate the UP9600 modem? I understand UP9600 is a cartridge. Is it correct?
Best!

**Comment by vbguyny** [comment]
Hello @jalbarracinv
Thank you for the kind words 🙂
I haven't discovered a way to make VICE work with UP9600. I did confirm that my kernel worked on an actual C64 bread in model using the WiFi64.

**Comment by jalbarracinv** [comment]
I am trying to find documentation on this UP9600 hack but with no luck. Do you have some info on this? best!! 
For example, does it works as Swiftlink with special addresses where the data have to be poked and peeked?
or Is it some "extension" to the actual RS-232 and it works with the same "open 15,8,15" commands

**Comment by vbguyny** [comment]
Hello @jalbarracinv 
Yea, documentation is very limited on how to use UP9600 and it has been over a year since I implemented in my Kernel so it isn't fresh in my mind.  However, I pulled the code from https://github.com/bozimmerman/Zimodem/blob/master/cbm8bit/src/up9600.asm however you can simply download the BIN file from the repo and following along with the documentation that I posted here: https://www.lemon64.com/forum/viewtopic.php?t=72681&sid=06af58061480aad382ff2f531ae99528

You will need to load UP9600.BIN into memory address 51200 (or $C800) and then run SYS 51200.  After you return from that statement you should be able to communicate over RS-232 serial port at 9600 baud.  I am unsure if it works with Swiftlink as I don't have one to test with but I do know that it works with the WiFi64.

**Comment by jalbarracinv** [comment]
This helps me a lot!! thank you for your great help :)
